### ISSUE TITLE
Not working with Contao 4.7

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-url-rewrite#14]
I try to use the contao-url-rewrite in Contao 4.7. I set up the basic example with the "find/{address}" route. Though `vendor/bin/contao-console router:match /find/location` matches the defined route, I get an `NotFoundHttpException` exception 404 error in the frontend.

May this be caused by the new introduced symfony cmf router?

**Comment by dmolineus** [comment]
I found how why it doesn't work. Symfony creates a cached matcher class which contains all loaded routes. This means that the routes from url rewrite are only applied if the cache get's cleared.

Didn't find out when it's changed or if this issue exists all the time.

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-url-rewrite/commit/bd57ee4b4c5313954de5db8954b254f8c1f251ad and https://github.com/terminal42/contao-url-rewrite/commit/479bba06b53d48987685b1b126657b4dbebc5637.

**Comment by dmolineus** [comment]
This issue isn't fixed unfortunately. If I activate / deactivate an existing route I still have to warmup the symfony cache so that the changes are recognized.

**Comment by Toflar** [comment]
I cannot reproduce. Already works in production :)

**Comment by dmolineus** [comment]
Rechecked it. Forgot to update to Contao 4.7.2. Updating to Contao 4.7.2 solves the issue. Thanks.

**Comment by Toflar** [comment]
Cool, so I tag and release?

**Comment by dmolineus** [comment]
Yes :smile:
